programs:
  # Like bio, but with tracepoints. It may catch more than just bio, especially
  # if you have RAID, because requests are getting split and remapped.
  #
  # See:
  # * https://github.com/iovisor/bcc/issues/826
  - name: biolatency
    metrics:
      histograms:
        - name: bio_latency_seconds
          help: Block IO latency histogram
          table: io_latency
          bucket_type: exp2
          bucket_min: 0
          bucket_max: 26
          bucket_multiplier: 0.000001 # microseconds to seconds
          labels:
            - name: device
              size: 4
              decoders:
                - name: majorminor
            - name: flags
              size: 4
              decoders:
                - name: uint
                - name: static_map
                  static_map:
                    2048: NoWait
                    4096: Background
                    8192: ReadAhead
                    16384: PreFlush
                    32768: FUA
                    65536: Integrity
                    131072: Idle
                    262144: NoMerge
                    524288: Priority
                    1048576: Metadata
                    2097152: Sync
            - name: ops
              size: 4
              decoders:
                - name: uint
                - name: static_map
                  static_map:
                    0: Read
                    1: Write
                    2: Flush
                    3: Discard
                    5: SecureErase
                    6: ZoneReset
                    7: WriteSame
                    8: ZoneResetAll
                    9: WriteZeroes
                    10: ZoneOpen
                    11: ZoneClose
                    12: ZoneFinish
                    32: SCSIIn
                    33: SCSIOut
                    34: DrvIn
                    35: DrvOut
            - name: bucket
              size: 4
              decoders:
                - name: uint
        - name: bio_size_bytes
          help: Block IO size histogram with kibibyte buckets
          table: io_size
          bucket_type: exp2
          bucket_min: 0
          bucket_max: 15
          bucket_multiplier: 1024 # kibibytes to bytes
          labels:
            - name: device
              size: 4
              decoders:
                - name: majorminor
            - name: flags
              size: 4
              decoders:
                - name: uint
                - name: static_map
                  static_map:
                    2048: NoWait
                    4096: Background
                    8192: ReadAhead
                    16384: PreFlush
                    32768: FUA
                    65536: Integrity
                    131072: Idle
                    262144: NoMerge
                    524288: Priority
                    1048576: Metadata
                    2097152: Sync
            - name: ops
              size: 4
              decoders:
                - name: uint
                - name: static_map
                  static_map:
                    0: Read
                    1: Write
                    2: Flush
                    3: Discard
                    5: SecureErase
                    6: ZoneReset
                    7: WriteSame
                    8: ZoneResetAll
                    9: WriteZeroes
                    10: ZoneOpen
                    11: ZoneClose
                    12: ZoneFinish
                    32: SCSIIn
                    33: SCSIOut
                    34: DrvIn
                    35: DrvOut
            - name: bucket
              size: 4
              decoders:
                - name: uint
    raw_tracepoints:
      block_rq_issue: rawtracepoint__block_rq_issue
      block_rq_complete: rawtracepoint__block_rq_complete
      block_rq_insert: rawtracepoint__block_rq_insert
  - name: directreclaim
    metrics:
      histograms:
        - name: memory_direct_reclaim_latency
          help: memory direct latency histogram
          table: direct_reclaim_latency
          bucket_type: exp2
          bucket_min: 0
          bucket_max: 28
          bucket_multiplier: 0.000001 # microseconds to seconds
          labels:
            - name: bucket
              size: 8
              decoders:
                - name: uint
    tracepoints:
      vmscan:mm_vmscan_direct_reclaim_begin: tracepoint__vmscan__mm_vmscan_direct_reclaim_begin
      vmscan:mm_vmscan_direct_reclaim_end: tracepoint__vmscan__mm_vmscan_direct_reclaim_end
  # Track shrink_node latency, mainly for purposes of seeing latecy
  # of memory allocation slowpath.
  - name: shrinklat
    metrics:
      histograms:
        - name: shrink_node_latency_seconds
          help: Latency histogram for shrink_node calls
          table: shrink_node_latency
          bucket_type: exp2
          bucket_min: 0
          bucket_max: 26
          bucket_multiplier: 0.000001 # microseconds to seconds
          labels:
            - name: bucket
              size: 8
              decoders:
                - name: uint
    kprobes:
      shrink_node: kprobe__shrink_node
    kretprobes:
      shrink_node: kretprobe__shrink_node
  - name: kswapd
    metrics:
      counters:
        - name: kswapd
          help: kswapd wake count
          table: kswapd_counts
          labels:
            - name: numa_node
              size: 4
              decoders:
                - name: uint
            - name: numa_zone
              size: 4
              decoders:
                - name: uint
                - name: static_map
                  static_map:
                    0: DMA
                    1: DMA32
                    2: NORMAL
                    3: MOVEABLE
                    4: DEVICE
    tracepoints:
      vmscan:mm_vmscan_kswapd_wake: tracepoint__vmscan__mm_vmscan_kswapd_wake
  - name: kcompactd
    metrics:
      counters:
        - name: kcompactd_wake_count
          help: kcompactd wake count
          table: kcompactd_counts
          labels:
            - name: numa_node
              size: 4
              decoders:
                - name: uint
            - name: numa_zone
              size: 4
              decoders:
                - name: uint
                - name: static_map
                  static_map:
                    0: DMA
                    1: DMA32
                    2: NORMAL
                    3: MOVEABLE
                    4: DEVICE
    tracepoints:
      compaction:mm_compaction_kcompactd_wake: tracepoint__compaction__mm_compaction_kcompactd_wake
